### ISSUE TITLE
Single quotes break the summery

### ISSUE THREAD

**Issue by fabJunior** [ransurf/live-sync-inline-to-yaml#2]
# Problem
Unless I misunderstood how to use this plugin and/or Obsidian (very new to this) single quotes break the properties definition when using this plugin.

![Obsidian_NNBSr2SALd](https://github.com/ransurf/live-sync-inline-to-yaml/assets/16782977/6f869cd9-5df4-46a2-b550-9f3bc33ef2c3)

The reason is because of how the string is wrapped:
https://github.com/ransurf/live-sync-inline-to-yaml/blob/daa142d49731ad997af0ab2c5255df60a395d1b5/main.ts#L45-L59

The default case is to wrap the text in simple quotes.

# Proposed solution

To prevent formatting issues I'd suggest replacing all instances of `'` with two single quotes `''` (which is how Obsidian seems to escape simple quotes in simple quoted strings)

```ts
wrapInQuotationsIfString(value: string): string {

  // ...

  return `'${value.replaceAll("'", "''")}'`;
}
```

With that small edit, it's all fixed ! 🎉 

![Obsidian_QqdvtNfaZh](https://github.com/ransurf/live-sync-inline-to-yaml/assets/16782977/b52e26ae-cc09-4ec0-a334-5c02441f394a)

**Comment by ransurf** [comment]
Interesting, thank you for looking into it ! Can you fork and make a PR and
I'll approve it and add it to the new release? :)
